In [1]:
import numpy as np

In [10]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

In [16]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr1=np.array([my_lst1,my_lst2,my_lst3])

In [17]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [7]:
type(arr)

numpy.ndarray

In [8]:
## check the shape of the array

arr.shape

(3, 5)

## Indexing

In [11]:
## Accessing the array elements

arr

array([1, 2, 3, 4, 5])

In [12]:
arr[3]

4

In [18]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [19]:
arr1[1:,:2]

array([[2, 3],
       [9, 7]])

In [20]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [21]:
arr

array([1, 2, 3, 4, 5])

In [22]:
arr[3:]=100

In [23]:
arr

array([  1,   2,   3, 100, 100])

In [24]:
### Some conditions very useful in Exploratory Data Analysis 

val=2

arr[arr<3]

array([1, 2])

In [25]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [26]:
arr1=np.arange(0,10).reshape(2,5)

In [27]:
arr2=np.arange(0,10).reshape(2,5)

In [28]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [29]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [30]:
## random distribution
np.random.rand(3,3)

array([[0.94438892, 0.99322794, 0.29322583],
       [0.54584834, 0.41087225, 0.53547648],
       [0.45592503, 0.02867441, 0.98128843]])

In [31]:
arr_ex=np.random.randn(4,4)

In [32]:
arr_ex

array([[ 0.31191555, -0.99406877,  1.17861178, -0.83143493],
       [ 2.39168964, -0.14506176,  0.60667984,  1.66788645],
       [-0.36064402,  1.48459897, -0.03566993,  2.20649554],
       [-0.0899956 ,  0.91928179, -0.83734254,  1.46672668]])